[programs.localnet]
voter_weight_addin_deposits = "HoVX43xherfXV6RUoLmcoLA1XSyd9SbF4V1Edpi2QbLY"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
